export const GET_USER = 'GET_USER';
export const GET_INSTITUTIONS = 'GET_INSTITUTIONS';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
